name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # 매 step 기본 작업 경로를 my-portfolio로
    defaults:
      run:
        working-directory: my-portfolio

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # 캐시 키 생성에 사용할 lockfile 경로 지정
          cache-dependency-path: my-portfolio/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Test
        run: npm run test --if-present

      - name: Build
        run: npm run build

      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: my-portfolio/dist
