name: Update Progress Badge

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 매일 00:00 UTC (옵션)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Calc checklist progress (robust)
        id: calc
        shell: bash
        run: |
          FILE="README.md"

          # 총 체크박스:  - [ ]  또는  - [x]
          TOTAL=$(awk '
            BEGIN{c=0}
            /^[ \t]*-[ \t]*\[( |x|X)\]/ {c++}
            END{print c+0}
          ' "$FILE")

          # 완료 체크박스: - [x]
          DONE=$(awk '
            BEGIN{c=0}
            /^[ \t]*-[ \t]*\[(x|X)\]/ {c++}
            END{print c+0}
          ' "$FILE")

          # 퍼센트 (총=0이면 0)
          PCT=$(awk -v d="$DONE" -v t="$TOTAL" 'BEGIN{ if(t==0) print 0; else printf "%d", (d*100)/t }')

          echo "total=$TOTAL" >> "$GITHUB_OUTPUT"
          echo "done=$DONE" >> "$GITHUB_OUTPUT"
          echo "pct=$PCT"   >> "$GITHUB_OUTPUT"

      - name: Update badge in README
        shell: bash
        run: |
          PCT="${{ steps.calc.outputs.pct }}"
          COLOR="lightgrey"
          if   [ "$PCT" -ge 90 ]; then COLOR="brightgreen"
          elif [ "$PCT" -ge 70 ]; then COLOR="green"
          elif [ "$PCT" -ge 50 ]; then COLOR="yellow"
          elif [ "$PCT" -ge 30 ]; then COLOR="orange"
          else COLOR="lightgrey"; fi

          BADGE="![Progress](https://img.shields.io/badge/Progress-${PCT}%25-${COLOR})"

          awk -v badge="$BADGE" '
            BEGIN {
              start="<!--progress-badge-start-->";
              end  ="<!--progress-badge-end-->";
              in_section=0;
            }
            {
              if ($0 ~ start) { print $0; print badge; in_section=1; next }
              if ($0 ~ end)   { in_section=0 }
              if (in_section==0) print $0
            }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update progress badge to ${{ steps.calc.outputs.pct }}% (${{ steps.calc.outputs.done }}/${{ steps.calc.outputs.total }})"
            git push
          fi
